# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3633349de66681c0e5add6c2cfd46babd3aec391a6142bc64c1c8fd250989b3c3a335e4db9e8d5c5fc3961068121e85293ce0bb05f62e906df5d374955dd441

test:
  secret_key_base: 0d65faf1e5d0de95a5889cfdec097494ecee9de204e55b27364db0f54bc32a4b9568119f9cb335fbc51607627e0c47d831bf6428f50630dc8270f283ba6df230

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
